# Generated by Django 3.2.5 on 2021-07-09 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbs', models.CharField(max_length=10, verbose_name='Deuda SBS')),
                ('sentinel', models.CharField(max_length=10, verbose_name='Valoracion Sentinel')),
                ('puntuacion', models.CharField(max_length=10, verbose_name='Valoracion IA')),
                ('monto', models.CharField(max_length=10, verbose_name='Monto de Credito')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credito',
                'verbose_name_plural': 'Creditos',
                'ordering': ['user', 'puntuacion', 'monto', '-created'],
            },
        ),
    ]
