# Generated by Django 3.2.5 on 2021-07-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credito', '0002_alter_credito_sentinel'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='estadoCredito',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Denegado', 'Denegado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=10, verbose_name='Estado del credito'),
        ),
    ]
